apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sns-app-ingress
  namespace: sns
spec:
  rules:
    - host: sns.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sns-app
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-ingress
  namespace: rustfs
spec:
  rules:
    - host: rustfs.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-admin-ingress
  namespace: rustfs
spec:
  rules:
    - host: rustfs-admin.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-tcp
  namespace: postgres
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgres
          port: 5432
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis-tcp
  namespace: redis
spec:
  entryPoints:
    - redis
  routes:
    - match: HostSNI(`*`)
      services:
        - name: redis
          port: 6379
