apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sns-app-ingress
  namespace: sns
spec:
  rules:
    - host: sns.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sns-app
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-ingress
  namespace: rustfs
spec:
  rules:
    - host: rustfs.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-admin-ingress
  namespace: rustfs
spec:
  rules:
    - host: rustfs-admin.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9001
