apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sns-app-ingress
  namespace: sns
spec:
  rules:
    - host: sns.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sns-app
                port:
                  number: 8080
