apiVersion: v1
kind: Secret
metadata:
  name: sns-secret
  namespace: sns
type: Opaque
stringData:
  db-username: snsuser
  db-password: snspassword
  redis-password: snspassword
  rustfs-access-key: rustfsadmin
  rustfs-secret-key: rustfsadmin
