global:
  domain: argocd.localhost

configs:
  cm:
    timeout.reconciliation: 60s
  params:
    server.insecure: "true"

server:
  ingress:
    enabled: true
    hostname: argocd.localhost
    path: /
    pathType: Prefix
    tls: false

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  replicas: 0
